# -*- coding: utf-8 -*-
{
    'name': 'Hudson Indian Payroll',
    'version': '19.0.1.0.7',
    'category': 'Human Resources/Payroll',
    'summary': 'Indian Statutory Payroll Localization for Hudson HRMS',
    'author': 'Hudson Software Solutions',
    'depends': [
        'hr',
        'account',
        'hudson_payroll_base',
        'hudson_attendance_payroll_link',
    ],


    'data': [
        'security/ir.model.access.csv',
        'security/hds_in_bonus_security.xml',
        'security/hds_in_statutory_report_security.xml',
        'security/tds_declaration_security.xml',
        'data/hr_salary_rule_category.xml',
        'data/hr_salary_rule_hra_da_india.xml',
        'data/hr_rule_parameters.xml',
        'data/hr_salary_rule_pf.xml',
        'data/hr_salary_rule_esic.xml',
        'data/hr_salary_rule_lwf.xml',
        'data/hr_bonus_payroll_data.xml',
        'data/hr_salary_rules.xml',
        'data/hr_salary_rule_gratuity.xml',
        'data/hr_salary_rule_professional_tax.xml',
        'data/lwf_state_rate_data.xml',
        'data/pt_state_slab_data.xml',
        'data/pt_period_schedule_data.xml',
        
        
        'data/hds_pt_report_tiles.xml',
        'data/tds_financial_year_data.xml',
        'data/tds_tax_regime_data.xml',
        'data/tds_tax_slab_data.xml',
        'data/tds_surcharge_data.xml',
        'data/tds_rule_parameters.xml',
        'data/tds_section_config_data.xml',
        'data/hr_payroll_benefit_india_data.xml',
        'data/hds_payment_mode_data.xml',
        'views/hds_payment_mode_views.xml',
        'views/hds_in_statutory_report_views.xml',
        'views/hds_pt_report_wizard_views.xml',
        'views/hds_pt_report_tile_views.xml',
        'wizard/hds_esic_report_wizard_views.xml',
        'wizard/hds_gratuity_report_wizard_views.xml',
        'wizard/hds_lwf_report_wizard_views.xml',
        'wizard/hds_salary_register_wizard_views.xml',
        'wizard/hds_yearly_salary_employee_wizard_views.xml',
        'views/hds_salary_statement_report_views.xml',
        'views/payroll_menu_views.xml',
        'views/payroll_dashboard_views.xml',
        'wizard/tds_financial_year_wizard_views.xml',
        'views/tds_configuration_views.xml',
        'views/tds_section_declaration_views.xml',
        'views/tds_declaration_views.xml',
        'views/tds_lta_previous_employer_views.xml',
        'views/tds_house_property_loss_carryforward_views.xml',
        'views/lwf_state_rate_views.xml',
        'views/pt_state_slab_views.xml',
        'views/pt_period_schedule_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_payslip_views.xml',
        'views/hds_in_payroll_audit_views.xml',
        'wizard/hds_in_salary_revision_wizard_views.xml',
        'views/hds_in_salary_revision_views.xml',
        'wizard/hds_in_bonus_import_wizard_views.xml',
        'views/hds_in_bonus_views.xml',
        'views/hr_leave_type_views.xml',
        'views/res_config_settings_views.xml',
        'reports/report_statutory_tax_calculation_templates.xml',
        'reports/report_payslip_custom_template.xml',
        'reports/report_salary_reports_templates.xml',
        'data/payroll_spreadsheet_dashboard_data.xml',
    ],


    'assets': {
        'web.assets_backend': [
            'hudson_in_payroll/static/src/js/salary_revision_list_controller.js',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
