# -*- coding: utf-8 -*-
from . import hr_employee_type
from . import hr_salary_rule_category
from . import hr_payroll_structure_type
from . import hr_payroll_structure
from . import hr_rule_parameter
from . import hr_salary_rule
from . import hr_payslip_worked_days
from . import hr_payslip_input
from . import hr_payslip_line
from . import hr_payslip
from . import payment_advice
from . import hr_payslip_run_dep_summary
from . import hr_payslip_run
from . import hr_contract
from . import res_config_settings
from . import hr_payroll_headcount
from . import hr_payroll_dashboard_warning
from . import hr_payroll_benefit
from . import hr_salary_rule_section
