# -*- coding: utf-8 -*-
from . import res_company
from . import res_config_settings
from . import hds_in_payroll_audit
from . import hr_rule_parameter
from . import tds_lta_previous_employer
from . import tds_house_property_loss_carryforward
from . import hr_employee
from . import hr_salary_rule
from . import hr_contract
from . import hr_payslip
from . import hds_in_salary_revision
from . import lwf_state_rate
from . import hds_in_bonus
from . import pt_state_slab
from . import pt_period_schedule
from . import hds_in_statutory_report
from . import hds_pt_report_tile
from . import tds_financial_year
from . import tds_tax_regime
from . import tds_tax_slab
from . import tds_surcharge
from . import tds_tax_section_config
from . import tds_employee_home_loan
from . import tds_employee_tax_regime
from . import tds_employee_declaration
from . import tds_employee_declaration_line
from . import tds_employee_income_declaration
from . import tds_employee_80c_declaration
from . import tds_employee_80d_declaration
from . import tds_employee_hra_declaration
from . import tds_recalculation_schedule
from . import payroll_dashboard
from . import hr_leave_type
from . import hds_salary_statement_report
